### ISSUE TITLE
Inventory Sensor doesn't work in certain game on 0.17.68

### ISSUE THREAD

**Issue by robot256** [Yousei9/Inventory-Sensor#13]
I have a weird situation where in this one save files, item-sensors do not output any signals at all.  It does not seem to depend on what other mods I have installed, and I can't recreate it in a new save file with any combination of mods.  Any idea what's special about this one?

https://www.dropbox.com/s/e2a58sv0tu56kp8/rail%201k_Dispatcher_v66_alternate.zip?dl=0

**Comment by Yousei9** [comment]
Against the explicit warning, "Scan range" was changed from 1.5 to 0.2.
Changing Scan Offset and Scan Range will cause IS to stop working as intended.

**Comment by robot256** [comment]
Thank you for the quick response, sorry for the stupid question!

I investigated and found that the mod setting changed between my saves on March 5 and 6.  Both saves were on Factorio 0.17.6 and Inventory Sensor 0.7.0.  Only change in the mod list was removing the Accumulator Wagons mod, so it wasn't a migration issue.  No idea why I or it would have changed the Scan Range setting, but somehow I didn't notice until now.

**Comment by Yousei9** [comment]
There has been a bug in either 0.16 or 0.15 randomly changing mod settings. I don't know of any such bug in 0.17.
