### ISSUE TITLE
Sensors don't update when revived by script

### ISSUE THREAD

**Issue by axaluss** [Yousei9/Inventory-Sensor#16]
when sensor was placed from a blueprint, it's behaving like a filter of some kind.

**Comment by Yousei9** [comment]
I have no idea what you mean by "working as filter".

Blueprints or copy and paste works fine for me in Factorio 1.1.5 with IS 1.10.0

**Comment by axaluss** [comment]
latest stable factorio version is 1.0.0. 
The latest version of sensors i tried there does not work properly with blueprints/copy paste.

**Comment by Yousei9** [comment]
Since my code hasn't changed between 1.0 and 1.1 it's very likely a bug in base that has been fixed.
You either have to wait for 1.1 to go stable or switch to experimental.

**Comment by mythmon** [comment]
For me, having nanobots place a blueprinted inventory sensor causes it to keep what ever settings it was copied as, and never update again. I'm not sure if this is specific to nanobots though, it's just what I've seen in my play through so far before unlocking bots. So far I always have to delete the sensors and place them again manually without the blueprint for them to work.

**Comment by Yousei9** [comment]
So not blueprints, but another mod reviving ghosts causes issues.
That is possible, I never updated IS to use more recent script_raised events.
