### ISSUE TITLE
non-recoverable error when placed next to a nuclear reactor from the Realistic Reactors mod

### ISSUE THREAD

**Issue by diamond-lizard** [Yousei9/Inventory-Sensor#25]
When the inventory sensor was placed next to a nuclear reactor with the Realistic Reactors mod installed, the game crashed with this error:

```
The mod Inventory Sensor (1.10.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Inventory Sensor::on_tick (ID 0)
Value (470391973738637.000000) outside of range. The data type allows values from -2147483648 to 2147483647 in property tree at ROOT[2].count
stack traceback:
	[C]: in function '__newindex'
	__Inventory Sensor__/control.lua:446: in function 'UpdateSensor'
	__Inventory Sensor__/control.lua:176: in function <__Inventory Sensor__/control.lua:154>
```

**Comment by Yousei9** [comment]
Out of range error is fixed in next release.

However using Inventory Sensor on Realistic Reactors is pointless.
Sensors detect a dummy reactor containing dummy fuel. Adding a filter for that is pointless as these reactors already have a built in control panel with all readouts.
